removeCookie('baby');
$('#main_head').load('031main_head.html');
$('#head_wrapper').load('032head_wrapper.html');
$('#main_content .temaiandzhicai').load('033temaizhicai.html');
$('#main_content .mingdian').load('034mingdian.html');
$('#main_content .mengbao').load('035mengbao.html');
$('#main_content .meizhuang').load('036meizhuang.html');
$('#main_content .food').load('037food.html');
$('#main_content .baojian').load('038baojian.html');
$('#main_content .shuma').load('039shuma.html');
$('#main_content .qiche').load('0310qiche.html');
$('#main_content .fushi').load('0311fushi.html');
$('#main_content .jujia').load('0312jujia.html');
$('#main_content .yundong').load('0313yundong.html');
$('#main_content .zhongbiao').load('0314zhongbiao.html');
$('#main_content .wanju').load('0315wanju.html');
$('#main_content .guessLike').load('0316guessLike.html');
$('#main_content .links').load('0317links.html');
$('#go-top').load('0318gotop.html');
$('#w-footer').load('0319footer.html');